"""billing_subscriptions_provider_offer_id

Revision ID: 1dc53012ca93
Revises: 9f2d4a6c1b7e
Create Date: 2026-04-23 19:54:16.739167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc53012ca93'
down_revision: Union[str, None] = '9f2d4a6c1b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


_FK_BILLING_SUBS_COUPON = "fk_billing_subscriptions_coupon_id_billing_coupons"


def _column_names(inspector: sa.Inspector) -> set[str]:
    return {c["name"] for c in inspector.get_columns("billing_subscriptions")}


def _index_names(inspector: sa.Inspector) -> set[str]:
    return {ix["name"] for ix in inspector.get_indexes("billing_subscriptions")}


def _ensure_index(index_name: str, table: str, columns: list[str]) -> None:
    insp = sa.inspect(op.get_bind())
    if index_name not in _index_names(insp):
        op.create_index(index_name, table, columns, unique=False)


def upgrade() -> None:
    # Idempotent: a failed prior run may have applied columns/indexes before the SQLite FK error.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    cols = _column_names(inspector)

    if "provider_offer_id" not in cols:
        op.add_column("billing_subscriptions", sa.Column("provider_offer_id", sa.String(length=64), nullable=True))
    if "billing_phase" not in cols:
        op.add_column(
            "billing_subscriptions",
            sa.Column("billing_phase", sa.String(length=32), server_default=sa.text("'free'"), nullable=False),
        )
    if "trial_access_until" not in cols:
        op.add_column("billing_subscriptions", sa.Column("trial_access_until", sa.DateTime(), nullable=True))
    if "authenticated_at" not in cols:
        op.add_column("billing_subscriptions", sa.Column("authenticated_at", sa.DateTime(), nullable=True))
    if "coupon_id" not in cols:
        op.add_column("billing_subscriptions", sa.Column("coupon_id", sa.String(length=36), nullable=True))
    if "coupon_code_snapshot" not in cols:
        op.add_column("billing_subscriptions", sa.Column("coupon_code_snapshot", sa.String(length=64), nullable=True))
    if "last_invoice_id" not in cols:
        op.add_column("billing_subscriptions", sa.Column("last_invoice_id", sa.String(length=64), nullable=True))
    if "last_payment_id" not in cols:
        op.add_column("billing_subscriptions", sa.Column("last_payment_id", sa.String(length=64), nullable=True))

    _ensure_index(op.f("ix_billing_subscriptions_billing_phase"), "billing_subscriptions", ["billing_phase"])
    _ensure_index(
        op.f("ix_billing_subscriptions_coupon_code_snapshot"),
        "billing_subscriptions",
        ["coupon_code_snapshot"],
    )
    _ensure_index(op.f("ix_billing_subscriptions_coupon_id"), "billing_subscriptions", ["coupon_id"])
    _ensure_index(
        op.f("ix_billing_subscriptions_last_invoice_id"), "billing_subscriptions", ["last_invoice_id"]
    )
    _ensure_index(
        op.f("ix_billing_subscriptions_last_payment_id"), "billing_subscriptions", ["last_payment_id"]
    )
    _ensure_index(
        op.f("ix_billing_subscriptions_provider_offer_id"), "billing_subscriptions", ["provider_offer_id"]
    )

    # SQLite cannot ALTER TABLE to add FK; app/ORM still relate coupon_id; enforce on Postgres.
    if bind.dialect.name != "sqlite":
        inspector = sa.inspect(op.get_bind())
        fks = {fk["name"] for fk in inspector.get_foreign_keys("billing_subscriptions") if fk.get("name")}
        if _FK_BILLING_SUBS_COUPON not in fks:
            op.create_foreign_key(
                _FK_BILLING_SUBS_COUPON, "billing_subscriptions", "billing_coupons", ["coupon_id"], ["id"]
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name != "sqlite":
        op.drop_constraint(_FK_BILLING_SUBS_COUPON, "billing_subscriptions", type_="foreignkey")
    op.drop_index(op.f('ix_billing_subscriptions_provider_offer_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_last_payment_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_last_invoice_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_coupon_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_coupon_code_snapshot'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_billing_phase'), table_name='billing_subscriptions')
    op.drop_column('billing_subscriptions', 'last_payment_id')
    op.drop_column('billing_subscriptions', 'last_invoice_id')
    op.drop_column('billing_subscriptions', 'coupon_code_snapshot')
    op.drop_column('billing_subscriptions', 'coupon_id')
    op.drop_column('billing_subscriptions', 'authenticated_at')
    op.drop_column('billing_subscriptions', 'trial_access_until')
    op.drop_column('billing_subscriptions', 'billing_phase')
    op.drop_column('billing_subscriptions', 'provider_offer_id')
    # ### end Alembic commands ###
