"""add social_sessions

Revision ID: 2872bf17094d
Revises: a2b6f7e8d9c0
Create Date: 2026-04-12 19:26:08.981480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2872bf17094d'
down_revision: Union[str, None] = 'a2b6f7e8d9c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
