"""Init

Revision ID: 52f68d1edebc
Revises: 
Create Date: 2026-04-24 23:13:05.531194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52f68d1edebc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_email'), 'admins', ['email'], unique=True)
    op.create_table('billing_webhook_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('delivery_hash', sa.String(length=64), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('processing_status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_webhook_events_delivery_hash'), 'billing_webhook_events', ['delivery_hash'], unique=True)
    op.create_index(op.f('ix_billing_webhook_events_event_type'), 'billing_webhook_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_billing_webhook_events_processing_status'), 'billing_webhook_events', ['processing_status'], unique=False)
    op.create_index(op.f('ix_billing_webhook_events_provider'), 'billing_webhook_events', ['provider'], unique=False)
    op.create_index(op.f('ix_billing_webhook_events_provider_subscription_id'), 'billing_webhook_events', ['provider_subscription_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('long_term_context', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.create_table('usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('minutes_used', sa.Float(), nullable=True),
    sa.Column('llm_output_tokens', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('stt_seconds', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('tts_seconds', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('chat_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('voice_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_date'), 'usage', ['date'], unique=False)
    op.create_index(op.f('ix_usage_id'), 'usage', ['id'], unique=False)
    op.create_index(op.f('ix_usage_user_id'), 'usage', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('native_language', sa.String(length=100), nullable=True),
    sa.Column('native_language_code', sa.String(length=16), nullable=True),
    sa.Column('student_type', sa.String(length=32), nullable=True),
    sa.Column('occupation', sa.String(length=32), nullable=True),
    sa.Column('goal', sa.String(length=64), nullable=True),
    sa.Column('english_level', sa.String(length=32), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('plan', sa.String(length=32), server_default=sa.text("'free'"), nullable=False),
    sa.Column('trial_expires_at', sa.DateTime(), nullable=True),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_trial_used', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_provider_id'), 'users', ['provider_id'], unique=False)
    op.create_table('billing_coupons',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'enabled'"), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('applies_to_plan_code', sa.String(length=32), nullable=False),
    sa.Column('free_cycles', sa.Integer(), nullable=True),
    sa.Column('discount_type', sa.String(length=32), nullable=True),
    sa.Column('discount_value', sa.Integer(), nullable=True),
    sa.Column('max_redemptions_total', sa.Integer(), nullable=True),
    sa.Column('max_redemptions_per_user', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('razorpay_offer_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('raw_config', sa.JSON(), nullable=True),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['updated_by_admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_coupons_applies_to_plan_code'), 'billing_coupons', ['applies_to_plan_code'], unique=False)
    op.create_index(op.f('ix_billing_coupons_code'), 'billing_coupons', ['code'], unique=True)
    op.create_index(op.f('ix_billing_coupons_created_by_admin_id'), 'billing_coupons', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_billing_coupons_mode'), 'billing_coupons', ['mode'], unique=False)
    op.create_index(op.f('ix_billing_coupons_razorpay_offer_id'), 'billing_coupons', ['razorpay_offer_id'], unique=False)
    op.create_index(op.f('ix_billing_coupons_status'), 'billing_coupons', ['status'], unique=False)
    op.create_index(op.f('ix_billing_coupons_updated_by_admin_id'), 'billing_coupons', ['updated_by_admin_id'], unique=False)
    op.create_table('live_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=True),
    sa.Column('client_platform', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_sessions_conversation_id'), 'live_sessions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_live_sessions_last_seen_at'), 'live_sessions', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_live_sessions_started_at'), 'live_sessions', ['started_at'], unique=False)
    op.create_index(op.f('ix_live_sessions_user_id'), 'live_sessions', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=False),
    sa.Column('client_turn_id', sa.String(length=36), nullable=True),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('ai_reply', sa.Text(), nullable=False),
    sa.Column('reply_language', sa.String(length=16), nullable=True),
    sa.Column('translated_ai_reply', sa.Text(), nullable=True),
    sa.Column('translation_language_code', sa.String(length=16), nullable=True),
    sa.Column('correction', sa.Text(), nullable=True),
    sa.Column('hinglish_explanation', sa.Text(), nullable=True),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_audio_url', sa.String(length=512), nullable=True),
    sa.Column('ai_reply_audio_storage_ref', sa.String(length=1024), nullable=True),
    sa.Column('translated_ai_reply_audio_storage_ref', sa.String(length=1024), nullable=True),
    sa.Column('explanation_audio_storage_ref', sa.String(length=1024), nullable=True),
    sa.Column('example_audio_storage_ref', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_client_turn_id'), 'messages', ['client_turn_id'], unique=False)
    op.create_index('ix_messages_conversation_created', 'messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index('ix_messages_conversation_id_id', 'messages', ['conversation_id', 'id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_table('social_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user1_id', sa.String(length=36), nullable=False),
    sa.Column('user2_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('agora_channel', sa.String(length=128), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_sessions_agora_channel'), 'social_sessions', ['agora_channel'], unique=True)
    op.create_index(op.f('ix_social_sessions_user1_id'), 'social_sessions', ['user1_id'], unique=False)
    op.create_index(op.f('ix_social_sessions_user2_id'), 'social_sessions', ['user2_id'], unique=False)
    op.create_table('voice_input_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('conversation_id', sa.String(), nullable=True),
    sa.Column('user_audio_url', sa.String(length=512), nullable=False),
    sa.Column('user_audio_storage_key', sa.String(length=1024), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=False),
    sa.Column('detected_lang', sa.String(length=16), nullable=True),
    sa.Column('transcript_source', sa.String(length=32), server_default=sa.text("'backend_final'"), nullable=False),
    sa.Column('warning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_input_drafts_conversation_id'), 'voice_input_drafts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_voice_input_drafts_created_at'), 'voice_input_drafts', ['created_at'], unique=False)
    op.create_index(op.f('ix_voice_input_drafts_expires_at'), 'voice_input_drafts', ['expires_at'], unique=False)
    op.create_index(op.f('ix_voice_input_drafts_status'), 'voice_input_drafts', ['status'], unique=False)
    op.create_index(op.f('ix_voice_input_drafts_user_id'), 'voice_input_drafts', ['user_id'], unique=False)
    op.create_table('billing_subscriptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('plan_code', sa.String(length=32), nullable=False),
    sa.Column('provider_plan_id', sa.String(length=64), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=64), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=64), nullable=True),
    sa.Column('provider_payment_id', sa.String(length=64), nullable=True),
    sa.Column('provider_offer_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('billing_phase', sa.String(length=32), server_default=sa.text("'free'"), nullable=False),
    sa.Column('short_url', sa.Text(), nullable=True),
    sa.Column('current_start_at', sa.DateTime(), nullable=True),
    sa.Column('current_end_at', sa.DateTime(), nullable=True),
    sa.Column('charge_at', sa.DateTime(), nullable=True),
    sa.Column('start_at', sa.DateTime(), nullable=True),
    sa.Column('end_at', sa.DateTime(), nullable=True),
    sa.Column('expire_by', sa.DateTime(), nullable=True),
    sa.Column('trial_access_until', sa.DateTime(), nullable=True),
    sa.Column('authenticated_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_cycle_end', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('coupon_id', sa.String(length=36), nullable=True),
    sa.Column('coupon_code_snapshot', sa.String(length=64), nullable=True),
    sa.Column('last_invoice_id', sa.String(length=64), nullable=True),
    sa.Column('last_payment_id', sa.String(length=64), nullable=True),
    sa.Column('raw_last_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['billing_coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_subscriptions_billing_phase'), 'billing_subscriptions', ['billing_phase'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_coupon_code_snapshot'), 'billing_subscriptions', ['coupon_code_snapshot'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_coupon_id'), 'billing_subscriptions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_last_invoice_id'), 'billing_subscriptions', ['last_invoice_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_last_payment_id'), 'billing_subscriptions', ['last_payment_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_plan_code'), 'billing_subscriptions', ['plan_code'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider'), 'billing_subscriptions', ['provider'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_customer_id'), 'billing_subscriptions', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_offer_id'), 'billing_subscriptions', ['provider_offer_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_payment_id'), 'billing_subscriptions', ['provider_payment_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_plan_id'), 'billing_subscriptions', ['provider_plan_id'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_provider_subscription_id'), 'billing_subscriptions', ['provider_subscription_id'], unique=True)
    op.create_index(op.f('ix_billing_subscriptions_status'), 'billing_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_billing_subscriptions_user_id'), 'billing_subscriptions', ['user_id'], unique=False)
    op.create_table('billing_coupon_redemptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('coupon_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('billing_subscription_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'reserved'"), nullable=False),
    sa.Column('coupon_code_snapshot', sa.String(length=64), nullable=False),
    sa.Column('effect_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_subscription_id'], ['billing_subscriptions.id'], ),
    sa.ForeignKeyConstraint(['coupon_id'], ['billing_coupons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_coupon_redemptions_billing_subscription_id'), 'billing_coupon_redemptions', ['billing_subscription_id'], unique=False)
    op.create_index(op.f('ix_billing_coupon_redemptions_coupon_code_snapshot'), 'billing_coupon_redemptions', ['coupon_code_snapshot'], unique=False)
    op.create_index(op.f('ix_billing_coupon_redemptions_coupon_id'), 'billing_coupon_redemptions', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_billing_coupon_redemptions_status'), 'billing_coupon_redemptions', ['status'], unique=False)
    op.create_index(op.f('ix_billing_coupon_redemptions_user_id'), 'billing_coupon_redemptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_coupon_redemptions_user_id'), table_name='billing_coupon_redemptions')
    op.drop_index(op.f('ix_billing_coupon_redemptions_status'), table_name='billing_coupon_redemptions')
    op.drop_index(op.f('ix_billing_coupon_redemptions_coupon_id'), table_name='billing_coupon_redemptions')
    op.drop_index(op.f('ix_billing_coupon_redemptions_coupon_code_snapshot'), table_name='billing_coupon_redemptions')
    op.drop_index(op.f('ix_billing_coupon_redemptions_billing_subscription_id'), table_name='billing_coupon_redemptions')
    op.drop_table('billing_coupon_redemptions')
    op.drop_index(op.f('ix_billing_subscriptions_user_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_status'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_subscription_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_plan_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_payment_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_offer_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider_customer_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_provider'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_plan_code'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_last_payment_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_last_invoice_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_coupon_id'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_coupon_code_snapshot'), table_name='billing_subscriptions')
    op.drop_index(op.f('ix_billing_subscriptions_billing_phase'), table_name='billing_subscriptions')
    op.drop_table('billing_subscriptions')
    op.drop_index(op.f('ix_voice_input_drafts_user_id'), table_name='voice_input_drafts')
    op.drop_index(op.f('ix_voice_input_drafts_status'), table_name='voice_input_drafts')
    op.drop_index(op.f('ix_voice_input_drafts_expires_at'), table_name='voice_input_drafts')
    op.drop_index(op.f('ix_voice_input_drafts_created_at'), table_name='voice_input_drafts')
    op.drop_index(op.f('ix_voice_input_drafts_conversation_id'), table_name='voice_input_drafts')
    op.drop_table('voice_input_drafts')
    op.drop_index(op.f('ix_social_sessions_user2_id'), table_name='social_sessions')
    op.drop_index(op.f('ix_social_sessions_user1_id'), table_name='social_sessions')
    op.drop_index(op.f('ix_social_sessions_agora_channel'), table_name='social_sessions')
    op.drop_table('social_sessions')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index('ix_messages_conversation_id_id', table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index('ix_messages_conversation_created', table_name='messages')
    op.drop_index(op.f('ix_messages_client_turn_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_live_sessions_user_id'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_started_at'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_last_seen_at'), table_name='live_sessions')
    op.drop_index(op.f('ix_live_sessions_conversation_id'), table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_index(op.f('ix_billing_coupons_updated_by_admin_id'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_status'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_razorpay_offer_id'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_mode'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_created_by_admin_id'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_code'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_applies_to_plan_code'), table_name='billing_coupons')
    op.drop_table('billing_coupons')
    op.drop_index(op.f('ix_users_provider_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_user_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_id'), table_name='usage')
    op.drop_index(op.f('ix_usage_date'), table_name='usage')
    op.drop_table('usage')
    op.drop_index('ix_conversations_user_updated', table_name='conversations')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_billing_webhook_events_provider_subscription_id'), table_name='billing_webhook_events')
    op.drop_index(op.f('ix_billing_webhook_events_provider'), table_name='billing_webhook_events')
    op.drop_index(op.f('ix_billing_webhook_events_processing_status'), table_name='billing_webhook_events')
    op.drop_index(op.f('ix_billing_webhook_events_event_type'), table_name='billing_webhook_events')
    op.drop_index(op.f('ix_billing_webhook_events_delivery_hash'), table_name='billing_webhook_events')
    op.drop_table('billing_webhook_events')
    op.drop_index(op.f('ix_admins_email'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
