"""live_session_heartbeat_status

Revision ID: af9750fb2202
Revises: 2872bf17094d
Create Date: 2026-04-16 15:50:39.193659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af9750fb2202'
down_revision: Union[str, None] = '2872bf17094d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('live_sessions', sa.Column('last_seen_at', sa.DateTime(), nullable=True))
    op.add_column('live_sessions', sa.Column('status', sa.String(length=16), server_default='active', nullable=False))
    op.create_index(op.f('ix_live_sessions_last_seen_at'), 'live_sessions', ['last_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_live_sessions_last_seen_at'), table_name='live_sessions')
    op.drop_column('live_sessions', 'status')
    op.drop_column('live_sessions', 'last_seen_at')
    # ### end Alembic commands ###
