"""ad_billing_subscriptions

Revision ID: c89cb5b7d265
Revises: 3e8503e5e3b9
Create Date: 2026-04-23 11:41:34.677595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c89cb5b7d265'
down_revision: Union[str, None] = '3e8503e5e3b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
