"""add_conversation_long_term_context

Revision ID: f29edc76160c
Revises: 258716de770d
Create Date: 2026-02-15 00:45:20.467062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f29edc76160c'
down_revision: Union[str, None] = '258716de770d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('long_term_context', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'long_term_context')
    # ### end Alembic commands ###
